// extract-brand-bits.ts — pull the designer's actual working parts out of the
// Instagram-story exploration exports: the chunky FOLD logotype, the organic
// frame shapes (blob, drape), and the embedded photos. These are the canon
// ingredients the composer builds with.
// Run: bun scripts/extract-brand-bits.ts

import { mkdirSync, writeFileSync, readFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "..");
const SRC = join(ROOT, "assets", "figma", "fold-brand");
const MARKS = join(ROOT, "public", "marks");
const PHOTOS = join(ROOT, "public", "photos");
mkdirSync(PHOTOS, { recursive: true });

const read = (f: string) => readFileSync(join(SRC, f), "utf8");

function paths(svg: string): { d: string; fill: string }[] {
  return [...svg.matchAll(/<path d="([^"]+)" fill="([^"]+)"/g)].map((m) => ({
    d: m[1],
    fill: m[2],
  }));
}

// Control-point bbox: Bezier curves stay inside their control hull, so the
// min/max of every coordinate in the path is a safe (slightly loose) bbox.
function bbox(d: string) {
  const nums = [...d.matchAll(/(-?\d*\.?\d+)[ ,](-?\d*\.?\d+)/g)].map((m) => [
    Number(m[1]),
    Number(m[2]),
  ]);
  const xs = nums.map((n) => n[0]);
  const ys = nums.map((n) => n[1]);
  const x = Math.min(...xs), y = Math.min(...ys);
  return { x, y, w: Math.max(...xs) - x, h: Math.max(...ys) - y };
}

// ---- 1. FOLD logotype (white glyph path in every story export) --------------
const story2 = read("instagram-story-2__4-78.svg");
const logo = paths(story2).find((p) => p.fill === "white")!;
const lb = bbox(logo.d);
const pad = lb.h * 0.04;
writeFileSync(
  join(MARKS, "fold-logotype.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${(lb.x - pad).toFixed(1)} ${(lb.y - pad).toFixed(1)} ${(lb.w + pad * 2).toFixed(1)} ${(lb.h + pad * 2).toFixed(1)}"><path d="${logo.d}" fill="currentColor"/></svg>`
);
console.log(`✓ fold-logotype.svg (${lb.w.toFixed(0)}×${lb.h.toFixed(0)})`);

// ---- 2. Designer frame shapes ----------------------------------------------
const shapes: { id: string; d: string; x: number; y: number; w: number; h: number }[] = [];
const addShape = (id: string, d: string) => {
  const b = bbox(d);
  shapes.push({ id, d, x: b.x, y: b.y, w: b.w, h: b.h });
  console.log(`✓ shape ${id} (${b.w.toFixed(0)}×${b.h.toFixed(0)})`);
};
addShape("blob", paths(story2).find((p) => p.fill === "#DD6232")!.d);
addShape(
  "drape",
  paths(read("instagram-story-3__7-19.svg")).find((p) => p.fill === "#D9D9D9")!.d
);
for (const [i, p] of paths(read("instagram-story-6__7-37.svg"))
  .filter((p) => p.fill === "#D9D9D9" || p.fill === "#DD6232")
  .entries())
  addShape(`shape6-${i}`, p.d);

writeFileSync(
  join(ROOT, "src", "frames", "designerShapes.ts"),
  `// GENERATED by scripts/extract-brand-bits.ts — the designer's own frame
// shapes traced from the Instagram-story explorations. Do not hand-edit.
export interface DesignerShape { id: string; d: string; x: number; y: number; w: number; h: number }
export const DESIGNER_SHAPES: DesignerShape[] = ${JSON.stringify(shapes, null, 2)};
`
);

// ---- 3. Embedded photos ------------------------------------------------------
const photoSrcs: [string, string][] = [
  ["instagram-story-4__7-23.svg", "gather-flute"],
  ["instagram-story-5__7-32.svg", "photo-b"],
  ["instagram-story-7__7-44.svg", "photo-c"],
  ["media__7-14.svg", "photo-d"],
  ["media__200-309.svg", "photo-e"],
];
const manifest: { id: string; file: string }[] = [];
const seen = new Set<string>();
for (const [file, id] of photoSrcs) {
  const svg = read(file);
  const m = svg.match(/data:image\/(jpeg|png);base64,([A-Za-z0-9+/=\s]+)/);
  if (!m) {
    console.log(`· ${file}: no embedded image`);
    continue;
  }
  const buf = Buffer.from(m[2].replace(/\s+/g, ""), "base64");
  const sig = buf.subarray(0, 512).toString("hex");
  if (seen.has(sig)) {
    console.log(`· ${file}: duplicate photo, skipped`);
    continue;
  }
  seen.add(sig);
  const ext = m[1] === "png" ? "png" : "jpg";
  const out = `${id}.${ext}`;
  writeFileSync(join(PHOTOS, out), buf);
  manifest.push({ id, file: out });
  console.log(`✓ photo ${out} (${(buf.length / 1024).toFixed(0)} KB)`);
}
writeFileSync(join(PHOTOS, "manifest.json"), JSON.stringify(manifest, null, 2));
console.log(`✓ manifest.json (${manifest.length} photos)`);
